### ISSUE TITLE
`Node.js 16 actions are deprecated` warning

### ISSUE THREAD

**Issue by e965** [dtinth/setup-github-actions-caching-for-turbo#21]
Hi!

Can you please upgrade the Node version in action? Github is swearing at it.

![image](https://github.com/dtinth/setup-github-actions-caching-for-turbo/assets/18071040/fcfe3561-e209-4a90-83de-a6c7a81a8667)

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by dtinth** [comment]
Hi, thanks for reporting this issue. I don’t have the bandwidth to dig into this right now, a PR is welcome! 🙏
