### ISSUE TITLE
Warn and handle failed cache-restoration (HTTP 500) instead of failing the pipeline

### ISSUE THREAD

**Issue by Addono** [dtinth/setup-github-actions-caching-for-turbo#23]
Hey! Thanks for creating this action! It has been really easy to get it up and running, and is a real value add!

We've now been using it for a couple of months, with recently sometimes cache-restoration failing and causing the entire pipeline to fail:
<img width="938" alt="image" src="https://github.com/dtinth/setup-github-actions-caching-for-turbo/assets/15435678/cd22e4e5-ecbd-405a-911b-91dccaf9c6f2">

Typically this error seems persistent for that specific cache key (sounds like something is going on with GitHub Action's Cache), thus we need to manually evict those cache keys before rerunning the pipeline.

What would it take to adjust the behavior such that it merely warns and considers this a cache-miss? Since caching is just a performance improvement, that would be preferable to us over requiring manual intervention.

**Comment by Addono** [comment]
I was digging a bit further into the logs, we're receiving a 409 when trying to reserve the cache key. I'm guessing this happens when multiple cache-restorations try to write at the same time? Would kind-of explain why deleting keys would solve it: We get cache-misses, thus all our parallel stages will have to actually do work, thus they de-sync when trying to persist the layers.

```
{
  "level": 50,
  "time": 1710499247729,
  "pid": 1564,
  "hostname": "fv-az1802-906",
  "reqId": "req-v",
  "req": {
    "method": "PUT",
    "url": "/v8/artifacts/87aa2369542e8d53?slug=turbogha",
    "hostname": "localhost:41230",
    "remoteAddress": "::1",
    "remotePort": 58452
  },
  "res": {
    "statusCode": 500
  },
  "err": {
    "type": "Error",
    "message": "Unable to reserve cache: Request failed with status code 409: Request failed with status code 409",
    "stack": "Error: Unable to reserve cache: Request failed with status code 409\n    at /home/runner/work/_actions/dtinth/setup-github-actions-caching-for-turbo/v1.2.0/webpack:/typescript-action/lib/main.js:249:1\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\ncaused by: AxiosError: Request failed with status code 409\n    at settle (/home/runner/work/_actions/dtinth/setup-github-actions-caching-for-turbo/v1.2.0/webpack:/typescript-action/node_modules/.pnpm/axios@1.6.6/node_modules/axios/dist/node/axios.cjs:1970:1)\n    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/dtinth/setup-github-actions-caching-for-turbo/v1.2.0/webpack:/typescript-action/node_modules/.pnpm/axios@1.6.6/node_modules/axios/dist/node/axios.cjs:3069:1)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1408:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/home/runner/work/_actions/dtinth/setup-github-actions-caching-for-turbo/v1.2.0/webpack:/typescript-action/node_modules/.pnpm/axios@1.6.6/node_modules/axios/dist/node/axios.cjs:3879:1)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
  },
  "msg": "Unable to reserve cache: Request failed with status code 409"
}

```

**Comment by Addono** [comment]
I hacked together a fix in my fork: https://github.com/Addono/setup-github-actions-caching-for-turbo/commit/78e76726e095106f4dacd5aa366e7c9a00af897f

Will use it for a bit and see if the problem is now gone :)

If it does we can see whether it would be something you're interested in having included into upstream.

**Comment by Addono** [comment]
Check. Happy to be of help.

This action has paid back big time given how easy it has been to get it to work and just been paying returns ever since. (We did learn the hard way that our Turbo config wasn't always correct 🙃  but that was 100% on us).

There's a PR up - #24 - with the changes we've been running now for a week. Probably we've had 50-100 CI runs with it since, I haven't seen the issue come up when we started using the forked version.

**Comment by hirbod** [comment]
@Addono is there an easy way to use your fork?

**Comment by dtinth** [comment]
Thanks for the bump @hirbod

I'm currently overwhelmed and didn't manage to merge @Addono's PR #24 and release a new version. I hope to get back to this some time soon, sorry for the inconvenience...

**Comment by hirbod** [comment]
@dtinth thanks for the response. Appreciated!

**Comment by Addono** [comment]
> Thanks for the bump @hirbod
> 
> I'm currently overwhelmed and didn't manage to merge @Addono's PR #24 and release a new version. I hope to get back to this some time soon, sorry for the inconvenience...

No problem, fork has been working fine :) Whenever you've time take a look, no rush.
